version: '3.9'

services:
  web:
    build: .
    command: python /django-postgres-docker/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-postgres-docker
    ports:
      - 8000:8000
  db: 
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

